name: 'Install Java 11 and Ivy on Windows'
description: 'Installs Java 11 and Apache Ivy for Any on Windows (latest)'

inputs:
  ivy_version:
    description: 'which version of the ivy to install'
    required: true
  ivy_sha512:
    description: 'sha512 checksum of ivy distribution tar.gz file'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    - run: |
        Invoke-WebRequest https://dlcdn.apache.org//ant/ivy/$env:IVY_VERSION/apache-ivy-$env:IVY_VERSION-bin.tar.gz -OutFile apache-ivy-$env:IVY_VERSION-bin.tar.gz
        certutil.exe -hashfile apache-ivy-2.5.3-bin.tar.gz SHA512 | Out-File -FilePath download.sha512
        echo $env:IVY_SHA512 apache-ivy-$env:IVY_VERSION-bin.tar.gz > download.sha512sum
        if ((Get-Content -Path download.sha512)[1] -eq $env:IVY_SHA512) {
          tar.exe xzf apache-ivy-$env:IVY_VERSION-bin.tar.gz
          $env:ant_home = (ant get_ant_home | findstr.exe echo).split(' ', 2, [System.StringSplitOptions]::RemoveEmptyEntries)[1]
          Copy-Item -Path "apache-ivy-$env:IVY_VERSION/ivy-$env:IVY_VERSION.jar" -Destination "$env:ant_home/lib"
        } else {
          exit 1
        }
      shell: powershell
